services:
  chaekit-spring:
    build: .
    environment:
      # DB
      DB_URL: jdbc:mysql://chaekit-mysql:3306/chaekit
      DB_USERNAME: root
      DB_PASSWORD: 0000
      DB_DRIVER_CLASS: com.mysql.cj.jdbc.Driver
      JPA_DIALECT: org.hibernate.dialect.MySQL8Dialect

      # Redis
      REDIS_URL: chaekit-redis

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: 3600000
      JWT_REFRESH_EXPIRATION_MS: 1209600000

      # Admin
      ADMIN_NAME: admin
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      # GMAIL
      GMAIL_ADDRESS: ${GMAIL_ADDRESS}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}

      # Spring
      SPRING_PROFILES_ACTIVE: local

      # AWS
      EBOOK_BUCKET_NAME: chaekit
      IMAGE_BUCKET_NAME: chaekit-image
      AWS_S3_REGION: ap-northeast-2
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
      EBOOK_MAX_FILE_SIZE: 20971520
      PRESIGNED_URL_EXPIRATION_TIME: 3600

      # CORS
      CORS_ALLOWED_ORIGINS: http://localhost:5173,https://chaekit.com,https://*.chaekit.com

    depends_on:
      - chaekit-mysql
      - chaekit-redis
    ports:
      - "8080:8080"
  chaekit-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: chaekit
      MYSQL_ROOT_PASSWORD: 0000
    ports:
      - "3306:3306"
    volumes:
      - chaekit-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      retries: 10

  chaekit-redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10

volumes:
  chaekit-mysql-data:
