name: Task
description: 백로그에 작업를 등록합니다
title: "[TASK]"
labels: [Backlog]

body:
  - type: textarea
    id: goal
    attributes:
      label: 🎯 목표
      description: 이 작업을 통해 무엇을 해결하거나 구현하고자 하는지 간단히 작성해주세요.
      placeholder: |
        예) 회원가입 시 일반 사용자와 출판사를 구분하여 처리할 수 있도록 API를 분기합니다.
        예) 로그인 실패 시 클라이언트에 적절한 오류 메시지를 반환하도록 처리합니다.
    validations:
      required: true

  - type: textarea
    id: task-list
    attributes:
      label: ✅ 할 일
      placeholder: |
        - [ ] 기능 구현
        - [ ] 예외 처리
        - [ ] 테스트 작성
    validations:
      required: true

  - type: textarea
    id: note
    attributes:
      label: 🔗 비고