spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: ${JPA_DIALECT}
    show-sql: true


  config:
    import: optional:file:.env[.properties]

  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000
