spring:
  profiles:
    active: local # default profile
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: ${JPA_DIALECT}
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    baseline-version: 1
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADDRESS}
    password: ${GMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  config:
    import: optional:file:.env[.properties]


springdoc:
  swagger-ui:
    disable-swagger-default-url: true
jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION_MS}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  name: ${ADMIN_NAME}
aws:
  ebook-bucket-name: ${EBOOK_BUCKET_NAME}
  image-bucket-name: ${IMAGE_BUCKET_NAME}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${SECRET_ACCESS_KEY}
  ebook-max-file-size: ${EBOOK_MAX_FILE_SIZE}
  s3-region: ${AWS_S3_REGION}
  presigned-url-expiration-time: ${PRESIGNED_URL_EXPIRATION_TIME}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
