name: AWS CI CD
on:
  push:
    paths:
      - "chaekit-spring/**"
    branches:
      - feat/be/entity

permissions:
  id-token: write
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Change directory to chaekit-spring
        run: cd chaekit-spring

      # AWS 로그인
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::880996438467:role/allow
          role-session-name: sampleSessionName
          aws-region: ap-northeast-2

      #ECR에 로그인
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      #이미지를 빌드하고 ECR에 push
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: chaekit/chaekit_spirngbackend
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f chaekit-spring/Dockerfile chaekit-spring/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build Image Path
        id: image-path
        env:
          ECR_REGISTRY: 880996438467.dkr.ecr.ap-northeast-2.amazonaws.com
          ECR_REPOSITORY: chaekit/chaekit_spirngbackend
          IMAGE_TAG: latest
        run: |
          echo "ecs-deploy-image=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

      # task-definition.json 파일 내용 확인
      - name: Check task definition content
        run: |
          echo "Task Definition Content:"
          cat chaekit-spring/task-definition.json

      - name: Create ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: chaekit-spring/task-definition.json
          container-name: ecs-container
          image: ${{ steps.image-path.outputs.ecs-deploy-image }}
          environment-variables: |
            DB_URL=${{ secrets.DB_URL }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}

      - name: Deploy ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          cluster: chaekitcluster # 여러분의 ECS 클러스터 이름
          service: chaekit0411service # 여러분의 ECS 서비스 이름
          wait-for-service-stability: true
