name: PR Test

on:
  pull_request:
    paths:
      - "chaekit-spring/**"
    branches: [dev]

permissions: write-all

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chaekit-spring

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      # 테스트 + 커버리지 체크 (실패 시 중단됨)
      - name: Run tests with coverage
        run: ./gradlew test jacocoTestReport jacocoTestCoverageVerification

      - name: Test Coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.6
        with:
          title: Test Coverage Report
          paths: chaekit-spring/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 0
